// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skoosypvbcjjekhfjxrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrb29zeXB2YmNqamVraGZqeHJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDM0NTgsImV4cCI6MjA2MjcxOTQ1OH0.yKY9hXRok14AGXagNcFOqwJhUoKrC0fKhH-l1ZAWPk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);